# Generated by Django 6.0.4 on 2026-04-13 18:17

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('summary', models.TextField()),
                ('history_text', models.TextField(blank=True)),
                ('importance_text', models.TextField(blank=True)),
                ('rediscovery_path_json', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding (placeholder for pgvector)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('level', models.CharField(choices=[('HS', 'High School'), ('UNI', 'University'), ('OTH', 'Other')], default='HS', max_length=10)),
                ('curriculum_system', models.CharField(help_text='e.g., KCSE, CBC, IB', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide or FontAwesome icon name', max_length=50)),
                ('color', models.CharField(default='#000000', help_text='HEX color code for UI', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('entries_json', models.JSONField(default=list, help_text='List of timeline events')),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='content.concept')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('content_json', models.JSONField(blank=True, default=list, help_text='Denormalized cache of LessonSections')),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.concept')),
                ('tags', models.ManyToManyField(blank=True, related_name='lessons', to='content.curriculumtag')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'Text Block'), ('video', 'Video'), ('diagram', 'Diagram/Image'), ('interactive', 'Interactive Component'), ('lab', 'Virtual Lab'), ('socratic_pause', 'Socratic Pause Point')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('component_config', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('HS', 'High School'), ('UNI', 'University')], default='HS', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='content.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.subject')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='content.topic'),
        ),
        migrations.CreateModel(
            name='VirtualLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lab_type', models.CharField(help_text='e.g., titration, projectile', max_length=100)),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('simulation_mode', models.CharField(choices=[('client', 'Client-side only'), ('server', 'Server-supported')], default='client', max_length=10)),
                ('threejs_config', models.JSONField(blank=True, default=dict)),
                ('python_entry', models.CharField(blank=True, help_text='Path to server-side script if needed', max_length=255)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='content.concept')),
            ],
        ),
        migrations.CreateModel(
            name='WhyItMattersStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('narration_script', models.TextField()),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='content.concept')),
            ],
        ),
    ]
