# Generated by Django 6.0.4 on 2026-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='content.concept'),
        ),
        migrations.AddField(
            model_name='concept',
            name='x_pos',
            field=models.IntegerField(default=0, help_text='X coordinate on Knowledge Map'),
        ),
        migrations.AddField(
            model_name='concept',
            name='y_pos',
            field=models.IntegerField(default=0, help_text='Y coordinate on Knowledge Map'),
        ),
    ]
