# Generated by Django 6.0.4 on 2026-04-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_concept_prerequisites_concept_x_pos_concept_y_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('item_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('tf', 'True/False'), ('short', 'Short Answer')], default='mcq', max_length=10)),
                ('explanation', models.TextField(blank=True, help_text='Shown after answering')),
                ('difficulty', models.PositiveIntegerField(default=1)),
                ('p_slip', models.FloatField(default=0.1)),
                ('p_guess', models.FloatField(default=0.2)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='content.concept')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='content.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.assessmentitem')),
            ],
        ),
    ]
